### ISSUE TITLE
how should I use Jeo on this?

### ISSUE THREAD

**Issue by vjpixel** [oeco/jeo#20]
hi!

I'm planning a site that the main focus is projects. since some of this projects happen in events, I want to have a event list page in the site.

my question is: it's better to use Jeo for the whole site or to create one site and one hotsite that gets content from the events database and list?

thank you!

**Comment by miguelpeixe** [comment]
Since JEO is simple theme with lots of tools behind it, I'd recommend developing your own child theme to attend your purposes.

I'm not sure I got the "events" part right, but there's a [JEO child theme for events](https://github.com/cardume/feiradetrocas-wptheme), developed for [Feira de Trocas project](http://mobilizacao.alana.org.br/)

**Comment by vjpixel** [comment]
so I understand that the better approach is to create a child theme in Jeo that the default post type is not mapped, right?

**Comment by miguelpeixe** [comment]
That's a way to go.
You can hook the "mapable" post types with the `jeo_mapped_post_types` filter.

Defaults are all public post types registered, excluding pages.

Example:

``` php
function my_custom_mapped_post_type($post_types) {
  $post_types = array('event'); // Only my custom post type
  return $post_types
}
add_filter('jeo_mapped_post_types', 'my_custom_mapped_post_type');
```
