### ISSUE TITLE
Number of map markers on single post (single.php) template?

### ISSUE THREAD

**Issue by tehnit** [oeco/jeo#45]
Is there a possibility to show more then one marker on single post template?

e.g. When I open a post from featured map, can that post show me the map with all the associated markers, and not just the one marker that is associated with the post?

Thanks in advance.

**Comment by gufalei** [comment]
Originally there is no wizard or feature to do this on the original JEO WP .

What has been done in InfoAmazonia or Ekuatorial is to associate posts using categories or aggreagate posts on a specific map, or even the search

See if something like this works for you
http://infoamazonia.org/explore

Otherwise, let us know

**Comment by tehnit** [comment]
Eventually I used categories to show associated posts on the map, but what I wanted to accomplish is that when someone opens a post they see centered post marker of that post and all the rest viewable markers from that category, but the category alone did the trick.

Thanks for the reply.
