### ISSUE TITLE
Custom Logo for Jeo Theme

### ISSUE THREAD

**Issue by delir1um** [oeco/jeo#55]
Hi, First of all, Excellent work guys! I would like to know how I can integrate these features with an existing theme I have, as I would like to use my own logo and menu. Is there not a way to convert these theme features into a plugin of sorts? I wouldn't know where to start. Im pretty much a noob. Thanx for your time!

**Comment by gufalei** [comment]
@delir1um

With the current JEO theme you can customize all your logo and other design
needs.
What is the specific parts you are thinking could be a plugin?
Or you would consider a better option to have an online service from us,
instead of installing your own child theme?

2014-07-25 3:44 GMT-03:00 delir1um notifications@github.com:

> Hi, First of all, Excellent work guys! I would like to know how I can
> integrate these features with an existing theme I have, as I would like to
> use my own logo and menu. Is there not a way to convert these theme
> features into a plugin of sorts? I wouldn't know where to start. Im pretty
> much a noob. Thanx for your time!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/oeco/jeo/issues/55.

## 

Gustavo Faleiros

**Comment by delir1um** [comment]
Hi Gustavo, 

Where would I go to change the theme logo as an example? 

Kind Regards, 

Anton Vorster

On 2014-07-28 03:03, Gustavo Faleiros wrote: 

> @delir1um 
> 
> With the current JEO theme you can customize all your logo and other design 
> needs. 
> What is the specific parts you are thinking could be a plugin? 
> Or you would consider a better option to have an online service from us, 
> instead of installing your own child theme? 
> 
> 2014-07-25 3:44 GMT-03:00 delir1um notifications@github.com: 
> 
> > Hi, First of all, Excellent work guys! I would like to know how I can 
> > integrate these features with an existing theme I have, as I would like to 
> > use my own logo and menu. Is there not a way to convert these theme 
> > features into a plugin of sorts? I wouldn't know where to start. Im pretty 
> > much a noob. Thanx for your time! 
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub 
> > https://github.com/oeco/jeo/issues/55. 
> 
> ## 
> 
> Gustavo Faleiros 
> 
> ## 
> 
> Reply to this email directly or view it on GitHub [1].

## Links:

[1] https://github.com/oeco/jeo/issues/55#issuecomment-50292075

**Comment by miguelpeixe** [comment]
@delir1um 

Today all the features are attached to the theme. Since maps interactions are pretty much visual, we chose to use the concept of JEO being a parent theme with visual guidelines towards mapping, working pretting much as a framework and you can change the behaviour by customizing through child theming.

You **can** use JEO features outside of it's theme scope. All the core features are located on the `inc/` directory and connected to the theme through  `functions.php`. That means you can start a theme from scratch or integrate it with another. You might need analyse pretty closely how JEO as a theme uses the core functions to end up with all it's features.

**Comment by delir1um** [comment]
@miguelpeixe 

Thank you for your reply!. Is it possible to place a map in page content with shortcode or similar? I am only able to associate a post with a map, but I would like to place a map in a page. Thank you for your time!

**Comment by gufalei** [comment]
@delir1um

Try create categories like we have done in InfoAmazonia. So in this case
you can do a page with a map, for example
http://infoamazonia.org/maps/deforestation/

2014-07-28 15:31 GMT-03:00 delir1um notifications@github.com:

> @miguelpeixe https://github.com/miguelpeixe
> 
> Thank you for your reply!. Is it possible to place a map in page content
> with shortcode or similar? I am only able to associate a post with a map,
> but I would like to place a map in a page. Thank you for your time!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/oeco/jeo/issues/55#issuecomment-50378737.

## 

Gustavo Faleiros

**Comment by delir1um** [comment]
@gufalei 

Thank you, is there a demo site of InfoAmazonia where I can log in and see what was done in the backend as I cannot find any documentation on your suggestion. I'm missing something somewhere.

**Comment by delir1um** [comment]
@gufalei After many hours, I managed to figure out what needs to be done. Thank you!
